// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnjOPyLsaqbAMfhc65iEOdZ9X0Frf7WQ',
    appId: '1:594989544918:web:1283f71058300d5eb4e077',
    messagingSenderId: '594989544918',
    projectId: 'madrasatifinal',
    authDomain: 'madrasatifinal.firebaseapp.com',
    storageBucket: 'madrasatifinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28Mo1HoRDHTsZ6zsJPWjX5Z1eUcwcv4Q',
    appId: '1:594989544918:android:01962068189103b4b4e077',
    messagingSenderId: '594989544918',
    projectId: 'madrasatifinal',
    storageBucket: 'madrasatifinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkcSyGve13523FmJ13D6bI0zyjAkUCpY',
    appId: '1:594989544918:ios:2a42f93f99842451b4e077',
    messagingSenderId: '594989544918',
    projectId: 'madrasatifinal',
    storageBucket: 'madrasatifinal.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkcSyGve13523FmJ13D6bI0zyjAkUCpY',
    appId: '1:594989544918:ios:2a42f93f99842451b4e077',
    messagingSenderId: '594989544918',
    projectId: 'madrasatifinal',
    storageBucket: 'madrasatifinal.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiApp',
  );
}
